title: "Nikhil Sajimon"
description: "Portfolio of Data Engineering & Analytics Projects"
baseurl: "" # for GitHub Pages
url: "https://nikhilsajimon.github.io"
theme: chirpy

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-XXXXXXXXX-X # optional

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nikhil Sajimon"
