title: "Nikhil Sajimon"
description: "Portfolio of Data Science, ML, and Analytics Projects"
baseurl: "" # for GitHub Pages
url: "https://nikhilsajimon.github.io"
remote_theme: cotes2020/jekyll-theme-chirpy

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: G-GF67ZBK7J1

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Nikhil Sajimon"
